import { GroupExpense, Balance } from '@/hooks/useGroupExpenses';
import { GroupMember, Group } from '@/hooks/useGroups';
import { getCategoryById } from '@/lib/categories';
import { sumMoney, roundMoney } from '@/utils/money';
import { format } from 'date-fns';

export function exportSummaryReport(
  group: Group | undefined,
  expenses: GroupExpense[],
  balances: Balance[] = [],
  members: GroupMember[] = []
) {
  const groupName = group?.name || 'Group';
  const groupType = group?.type || 'Standard';
  const dateStr = format(new Date(), 'dd MMM yyyy, HH:mm');

  const validExpenses = expenses.filter((e) => e.category !== 'system');
  const totalSpent = sumMoney(validExpenses.map((e) => e.amount));
  const avgExpense = validExpenses.length > 0 ? roundMoney(totalSpent / validExpenses.length) : 0;

  // Category summary
  const categoryTotals = new Map<string, number>();
  validExpenses.forEach((e) => {
    const label = getCategoryById(e.category).label;
    categoryTotals.set(label, (categoryTotals.get(label) || 0) + e.amount);
  });

  // Member contributions
  const memberTotals = new Map<string, number>();
  validExpenses.forEach((e) => {
    const name = e.payer_name || 'Unknown';
    memberTotals.set(name, (memberTotals.get(name) || 0) + e.amount);
  });

  const memberRows = Array.from(memberTotals.entries())
    .map(([name, amount]) => `${name}: ₹${amount.toFixed(2)} (${totalSpent > 0 ? ((amount / totalSpent) * 100).toFixed(1) : 0}%)`)
    .join('\n  ');

  const categoryRows = Array.from(categoryTotals.entries())
    .map(([cat, amount]) => `${cat}: ₹${amount.toFixed(2)} (${totalSpent > 0 ? ((amount / totalSpent) * 100).toFixed(1) : 0}%)`)
    .join('\n  ');

  const balanceRows = balances.length > 0
    ? balances.map((b) => `${b.from_name} owes ${b.to_name}: ₹${b.amount.toFixed(2)}`).join('\n  ')
    : 'All members settled up (₹0.00 debt)';

  const reportText = `
==================================================
           EXPENSE SUMMARY & ANALYSIS REPORT
==================================================
Group Name   : ${groupName}
Group Type   : ${groupType}
Generated On : ${dateStr}
Total Spend  : ₹${totalSpent.toFixed(2)} (${validExpenses.length} expenses)
Average Spend: ₹${avgExpense.toFixed(2)} per expense
==================================================

PAID BY MEMBER:
  ${memberRows || 'No member payments recorded.'}

SPENDING BY CATEGORY:
  ${categoryRows || 'No category expenses recorded.'}

CURRENT OUTSTANDING BALANCES:
  ${balanceRows}

==================================================
      Report generated by Expense Manager App
==================================================
`.trim();

  // Create downloadable file
  const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${groupName.replace(/[^a-zA-Z0-9]/g, '_')}_Summary_Report.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
